wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    code_path: code/Train.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1649006175
    t:
      1:
      - 1
      4: 3.9.0
      5: 0.12.9
      8:
      - 3
      - 5
amp:
  desc: null
  value: false
batch_size:
  desc: null
  value: 5
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.0001
save_checkpoint:
  desc: null
  value: true
