wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    code_path: code/Run.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1650379163
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 15
      4: 3.9.0
      5: 0.12.14
      8:
      - 3
      - 5
amp:
  desc: null
  value: false
batch_size:
  desc: null
  value: 2
criterion:
  desc: null
  value: BCEWithLogitsLoss
device:
  desc: null
  value: cuda
epochs:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.001
model:
  desc: null
  value: MobileNetV2
name:
  desc: null
  value: 20220419_190923_MobileNetV2
optimizer:
  desc: null
  value: RMSprop
save_checkpoint:
  desc: null
  value: true
